export const SEED_COURSES = [
  // Programming
  {
    id: "prog-udemy-1",
    title: "The Complete Python Bootcamp From Zero to Hero in Python",
    category: "programming",
    provider: "Udemy",
    price: 1499,
    rating: 4.6,
    reviewsCount: 485120,
    duration: "22 hours",
    level: "Beginner",
    link: "https://www.udemy.com/courses/search/?q=programming%20courses&src=sgp",
    description: "Learn Python like a Professional. Start from the basics and go all the way to creating your own applications and games.",
    features: ["Certificate of completion", "Full lifetime access", "15 coding exercises", "Access on mobile and TV"]
  },
  {
    id: "prog-coursera-1",
    title: "Programming for Everybody (Getting Started with Python)",
    category: "programming",
    provider: "Coursera",
    price: 3299,
    rating: 4.8,
    reviewsCount: 290150,
    duration: "12 hours (1 month)",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=programming%20courses",
    description: "This course aims to teach everyone the basics of programming computers using Python.",
    features: ["Shareable certificate", "Flexible schedule", "Subtitles in 10+ languages", "Hands-on projects"]
  },
  {
    id: "prog-gl-1",
    title: "Java Programming Basics",
    category: "programming",
    provider: "Great Learning",
    price: 0,
    rating: 4.5,
    reviewsCount: 15400,
    duration: "2 hours",
    level: "Beginner",
    link: "https://www.mygreatlearning.com/academy/search?keyword=programming%20courses",
    description: "Master Java basics including variables, data types, operators, and loops to build a solid foundation.",
    features: ["Free certificate", "Self-paced learning", "1.5 hours of video content", "Lifetime access"]
  },
  {
    id: "prog-pwskills-1",
    title: "Full Stack Web Development (MERN Bootcamp)",
    category: "programming",
    provider: "PW Skills",
    price: 4999,
    rating: 4.7,
    reviewsCount: 12500,
    duration: "9 months",
    level: "Beginner",
    link: "https://pwskills.com/courses",
    description: "Comprehensive online boot camp training in HTML, CSS, JavaScript, Node.js, React.js, and SQL fundamentals.",
    features: ["Certificate of completion", "Doubt clearing support", "Industry projects", "Job portal access"]
  },
  
  // Data Science
  {
    id: "ds-udemy-1",
    title: "Python for Data Science and Machine Learning Bootcamp",
    category: "datascience",
    provider: "Udemy",
    price: 1999,
    rating: 4.7,
    reviewsCount: 125800,
    duration: "25 hours",
    level: "Intermediate",
    link: "https://www.udemy.com/courses/search/?q=data+science&src=sac&kw=data+sc",
    description: "Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Scikit-Learn, Machine Learning, and more!",
    features: ["Certificate of completion", "Lifetime access", "5 articles", "100+ lectures"]
  },
  {
    id: "ds-coursera-1",
    title: "IBM Data Science Professional Certificate",
    category: "datascience",
    provider: "Coursera",
    price: 4099,
    rating: 4.6,
    reviewsCount: 65200,
    duration: "5 months (10 hrs/week)",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=data%20science",
    description: "Kickstart your career in data science. Learn SQL, Python, data visualization, and build machine learning models.",
    features: ["Professional certificate", "10 course series", "Ace job interviews", "Applied learning portfolio"]
  },
  {
    id: "ds-gl-1",
    title: "Data Science Foundations",
    category: "datascience",
    provider: "Great Learning",
    price: 0,
    rating: 4.4,
    reviewsCount: 38700,
    duration: "2 hours",
    level: "Beginner",
    link: "https://www.mygreatlearning.com/academy/search?keyword=data%20science",
    description: "An introductory course to understand what Data Science is, its lifecycle, and basic applications.",
    features: ["Free certificate", "Self-paced", "Lifetime access", "Quizzes included"]
  },
  {
    id: "ds-simplilearn-1",
    title: "Post Graduate Program in Data Science",
    category: "datascience",
    provider: "Simplilearn",
    price: 54999,
    rating: 4.6,
    reviewsCount: 18400,
    duration: "11 months",
    level: "All Levels",
    link: "https://www.simplilearn.com",
    description: "Master Python, Machine Learning, Tableau, SQL in collaboration with Purdue University and IBM.",
    features: ["Purdue Certificate", "IBM masterclasses", "Capstone projects", "Co-op career services"]
  },

  // Design
  {
    id: "design-udemy-1",
    title: "Ultimate Photoshop Training: From Beginner to Pro",
    category: "design",
    provider: "Udemy",
    price: 1699,
    rating: 4.7,
    reviewsCount: 88400,
    duration: "15 hours",
    level: "All Levels",
    link: "https://www.udemy.com/courses/search/?q=designing%20courses",
    description: "Master Photoshop CC without previous knowledge. Learn photo editing, typography, and web UI layout creation.",
    features: ["Certificate of completion", "22 downloadable resources", "Lifetime access", "Mobile access"]
  },
  {
    id: "design-coursera-1",
    title: "Google UX Design Professional Certificate",
    category: "design",
    provider: "Coursera",
    price: 3299,
    rating: 4.8,
    reviewsCount: 78900,
    duration: "6 months (10 hrs/week)",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=designing%20courses",
    description: "Learn the foundations of UX design, build wireframes and prototypes, and conduct research to test your designs.",
    features: ["Professional certificate", "Portfolio projects", "7 course series", "Job placement support"]
  },

  // Cyber Security
  {
    id: "cyber-udemy-1",
    title: "The Complete Cyber Security Course: Hackers Exposed!",
    category: "cybersecurity",
    provider: "Udemy",
    price: 1299,
    rating: 4.5,
    reviewsCount: 145000,
    duration: "12 hours",
    level: "Beginner",
    link: "https://www.udemy.com/courses/search/?q=cybersecurity&src=sac&kw=cybersecurity",
    description: "Volume 1: Become a cyber security specialist. Learn how to stop hackers, prevent tracking, and protect privacy.",
    features: ["Certificate of completion", "1 downloadable resource", "Lifetime access", "Mobile/TV access"]
  },
  {
    id: "cyber-coursera-1",
    title: "Google Cybersecurity Professional Certificate",
    category: "cybersecurity",
    provider: "Coursera",
    price: 4099,
    rating: 4.8,
    reviewsCount: 32000,
    duration: "6 months (7 hrs/week)",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=cybersecurity",
    description: "Prepare for an entry-level job in cybersecurity. Learn Python, Linux, SQL, and SIEM tools.",
    features: ["Employer consortium access", "Ace interview prep", "8 course series", "Shareable certificate"]
  },
  {
    id: "cyber-gl-1",
    title: "Cyber Security Threats and Vulnerabilities",
    category: "cybersecurity",
    provider: "Great Learning",
    price: 0,
    rating: 4.6,
    reviewsCount: 9200,
    duration: "1.5 hours",
    level: "Beginner",
    link: "https://www.mygreatlearning.com/academy/search?keyword=cyber%20security",
    description: "Understand the various kinds of security threats, phishing, and software vulnerabilities.",
    features: ["Free certificate", "Self-paced", "Lifetime access", "Knowledge checks"]
  },
  {
    id: "cyber-simplilearn-1",
    title: "Cyber Security Expert Certificate Program",
    category: "cybersecurity",
    provider: "Simplilearn",
    price: 45000,
    rating: 4.5,
    reviewsCount: 6200,
    duration: "6 months",
    level: "Intermediate",
    link: "https://www.simplilearn.com",
    description: "Learn advanced cryptography, computer networks, risk management, and ethical hacking protocols.",
    features: ["Simplilearn Certification", "Hands-on labs", "CompTIA authorized partner", "24/7 learning assistance"]
  },

  // AI & Machine Learning
  {
    id: "ai-udemy-1",
    title: "Artificial Intelligence A-Z 2024: Build an AI",
    category: "aiml",
    provider: "Udemy",
    price: 1799,
    rating: 4.4,
    reviewsCount: 33400,
    duration: "16.5 hours",
    level: "Intermediate",
    link: "https://www.udemy.com/courses/search/?src=ukw&q=artificial+intelligence",
    description: "Combine Data Science, Machine Learning and Deep Learning to create powerful AI for Real-World applications.",
    features: ["Certificate of completion", "Code templates", "Lifetime access", "Q&A forum support"]
  },
  {
    id: "ai-coursera-1",
    title: "Supervised Machine Learning: Regression and Classification",
    category: "aiml",
    provider: "Coursera",
    price: 4099,
    rating: 4.9,
    reviewsCount: 182000,
    duration: "33 hours",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=machine%20learning",
    description: "Created by AI pioneer Andrew Ng. Build machine learning models in Python using NumPy and Scikit-learn.",
    features: ["Taught by Andrew Ng", "Flexible deadlines", "Hands-on coding labs", "Shareable certificate"]
  },
  {
    id: "ai-gl-1",
    title: "Introduction to Artificial Intelligence",
    category: "aiml",
    provider: "Great Learning",
    price: 0,
    rating: 4.5,
    reviewsCount: 44200,
    duration: "1.5 hours",
    level: "Beginner",
    link: "https://www.mygreatlearning.com/academy/search?keyword=artificial%20intelligence",
    description: "Learn the core definitions of AI, history, subsets like ML & DL, and modern application areas.",
    features: ["Free certificate", "Self-paced", "Lifetime access", "Video lessons"]
  },
  {
    id: "aiml-pwskills-1",
    title: "Practical Machine Learning & Deep Learning",
    category: "aiml",
    provider: "PW Skills",
    price: 5999,
    rating: 4.8,
    reviewsCount: 8900,
    duration: "6 months",
    level: "Beginner",
    link: "https://pwskills.com/courses",
    description: "Get a comprehensive introduction to machine learning algorithms, Neural Networks, PyTorch, and TensorFlow.",
    features: ["PW Skills Certificate", "1-on-1 mentorship", "Resume building", "Live coding labs"]
  },

  // Marketing
  {
    id: "mkt-udemy-1",
    title: "The Complete Digital Marketing Course - 12 Courses in 1",
    category: "marketing",
    provider: "Udemy",
    price: 1899,
    rating: 4.5,
    reviewsCount: 162000,
    duration: "22.5 hours",
    level: "All Levels",
    link: "https://www.udemy.com/courses/search/?q=digital+marketing&src=sac&kw=digital",
    description: "Master SEO, Facebook Marketing, YouTube Marketing, Google Adwords, Google Analytics, and more!",
    features: ["Certificate of completion", "36 articles", "10 downloadable resources", "Step-by-step guides"]
  },
  {
    id: "mkt-coursera-1",
    title: "Google Digital Marketing & E-commerce Certificate",
    category: "marketing",
    provider: "Coursera",
    price: 3299,
    rating: 4.8,
    reviewsCount: 22500,
    duration: "6 months (6 hrs/week)",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=digital%20marketing",
    description: "Learn the fundamentals of digital marketing and e-commerce, manage social media campaigns, and measure results.",
    features: ["Professional certificate", "CV & interview assistance", "Portfolio templates", "Employer portal access"]
  },

  // Cloud Computing & DevOps
  {
    id: "cloud-udemy-1",
    title: "Ultimate AWS Certified Solutions Architect Associate",
    category: "cloudcomputing",
    provider: "Udemy",
    price: 1699,
    rating: 4.7,
    reviewsCount: 198000,
    duration: "27 hours",
    level: "Intermediate",
    link: "https://www.udemy.com/courses/search/?q=aws+certified",
    description: "Pass the AWS Certified Solutions Architect Associate Certification. Learn all AWS fundamentals in detail.",
    features: ["Certificate of completion", "Practice exams", "Lifetime access", "Active student forum"]
  },
  {
    id: "cloud-coursera-1",
    title: "Google Cloud Digital Leader Training Professional Certificate",
    category: "cloudcomputing",
    provider: "Coursera",
    price: 3299,
    rating: 4.8,
    reviewsCount: 15400,
    duration: "16 hours",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=google%20cloud",
    description: "Learn Google Cloud basics, core services, security protocols, and how to operate cloud architectures.",
    features: ["Professional certificate", "Flexible deadlines", "100% online courses", "Hands-on cloud console labs"]
  },
  {
    id: "cloud-gl-1",
    title: "Cloud Computing Foundations",
    category: "cloudcomputing",
    provider: "Great Learning",
    price: 0,
    rating: 4.5,
    reviewsCount: 28500,
    duration: "2.5 hours",
    level: "Beginner",
    link: "https://www.mygreatlearning.com/academy/search?keyword=cloud%20computing",
    description: "Get introduced to cloud structures: SaaS, PaaS, IaaS, AWS architecture, and virtual servers.",
    features: ["Free certificate", "Self-paced", "Lifetime access", "Quiz assessment"]
  },
  {
    id: "blockchain-pwskills-1",
    title: "Smart Contract & DApp Development with Solidity",
    category: "cloudcomputing",
    provider: "PW Skills",
    price: 3499,
    rating: 4.6,
    reviewsCount: 3800,
    duration: "4 months",
    level: "Intermediate",
    link: "https://pwskills.com/courses",
    description: "Learn Ethereum programming, smart contract validation, Solidity compilation, and Web3 integration.",
    features: ["Certificate of completion", "Doubt support", "Project portfolio", "Placement help"]
  },

  // Project Management & Business
  {
    id: "pm-udemy-1",
    title: "PMP Exam Prep Seminar - Complete Exam Coverage",
    category: "business",
    provider: "Udemy",
    price: 1899,
    rating: 4.6,
    reviewsCount: 94000,
    duration: "35 hours",
    level: "Intermediate",
    link: "https://www.udemy.com/courses/search/?q=pmp+exam",
    description: "Earn 35 contact hours for the PMP exam. Complete coverage of PMBOK Guide 7th Edition concepts.",
    features: ["35 Contact Hours Certificate", "2 practice exams", "Lifetime access", "PMP application advice"]
  },
  {
    id: "pm-coursera-1",
    title: "Google Project Management Professional Certificate",
    category: "business",
    provider: "Coursera",
    price: 3299,
    rating: 4.8,
    reviewsCount: 61000,
    duration: "6 months (10 hrs/week)",
    level: "Beginner",
    link: "https://www.coursera.org/search?query=project%20management",
    description: "Prepare for a new career in project management. Learn agile systems, scrum, project documentation, and tools.",
    features: ["Professional certificate", "Resume builder access", "6 course series", "Ace interview preparation"]
  },

  // Swayam
  {
    id: "swayam-dsa-1",
    title: "Data Structures and Algorithms using Java",
    category: "programming",
    provider: "Swayam",
    price: 0,
    rating: 4.5,
    reviewsCount: 14200,
    duration: "12 weeks",
    level: "Intermediate",
    link: "https://swayam.gov.in",
    description: "Learn key data structures and algorithms in Java, designed by top IIT professors. Completely free with optional exam certificate.",
    features: ["Free access", "IIT credit-based syllabus", "Weekly assignments", "Optional exam certificate"]
  },
  {
    id: "swayam-ai-1",
    title: "Introduction to Artificial Intelligence",
    category: "aiml",
    provider: "Swayam",
    price: 0,
    rating: 4.4,
    reviewsCount: 11200,
    duration: "8 weeks",
    level: "Beginner",
    link: "https://swayam.gov.in",
    description: "Core foundations of artificial intelligence, search algorithms, state space search, and neural networks designed by IISc.",
    features: ["Free access", "IISc syllabus", "Video lectures", "Doubt forum"]
  },
  // Scrimba Programming
  {
    id: "prog-scrimba-1",
    title: "The Frontend Developer Career Path",
    category: "programming",
    provider: "Scrimba",
    price: 7999,
    rating: 4.9,
    reviewsCount: 8500,
    duration: "75 hours",
    level: "Beginner",
    link: "https://scrimba.com/learn/frontend",
    description: "Become a job-ready frontend developer. Learn HTML, CSS, JavaScript, React, and build dozens of interactive projects in a unique hands-on editor.",
    features: ["Shareable certificate", "Interactive code editor", "Community discord access", "Code reviews"]
  },
  // Advanced Programming
  {
    id: "prog-udemy-2",
    title: "JavaScript: The Advanced Concepts (2026)",
    category: "programming",
    provider: "Udemy",
    price: 1999,
    rating: 4.8,
    reviewsCount: 35600,
    duration: "25 hours",
    level: "Advanced",
    link: "https://www.udemy.com/courses/search/?q=javascript",
    description: "Learn modern advanced JavaScript practices and be in the top 10% of JavaScript developers. Master closures, prototypes, async, and OOP.",
    features: ["Certificate of completion", "Full lifetime access", "Access on mobile and TV", "24 articles"]
  },
  // DataCamp Data Science
  {
    id: "ds-datacamp-1",
    title: "Data Scientist with Python",
    category: "datascience",
    provider: "DataCamp",
    price: 9500,
    rating: 4.7,
    reviewsCount: 24200,
    duration: "88 hours",
    level: "Intermediate",
    link: "https://www.datacamp.com/tracks/data-scientist-with-python",
    description: "Gain the career-ready skills you need to start your journey as a data scientist. Learn to import, clean, manipulate, and analyze data.",
    features: ["DataCamp certification", "Interactive in-browser coding", "20+ course path", "Real-world projects"]
  },
  // Coursera Data Science
  {
    id: "ds-coursera-2",
    title: "Applied Data Science with Python Specialization",
    category: "datascience",
    provider: "Coursera",
    price: 3299,
    rating: 4.6,
    reviewsCount: 41000,
    duration: "5 months (10 hrs/week)",
    level: "Intermediate",
    link: "https://www.coursera.org/specializations/data-science-python",
    description: "Gain skills in data visualization, machine learning, text analysis, and social network analysis through popular python toolkits.",
    features: ["Shareable specialization certificate", "Taught by UMich faculty", "Hands-on programming assignments", "Flexible schedule"]
  },
  // IxDF UX Design
  {
    id: "design-interactive-1",
    title: "User Experience: The Ultimate Guide to UX/UI",
    category: "design",
    provider: "Interaction Design Foundation",
    price: 11200,
    rating: 4.8,
    reviewsCount: 15400,
    duration: "28 hours",
    level: "Beginner",
    link: "https://www.interaction-design.org/courses",
    description: "Get a comprehensive introduction to user experience design. Learn design thinking, user research, wireframing, and visual design.",
    features: ["IxDF Industry certificate", "Portfolio builder", "Taught by industry experts", "Lifetime course access"]
  },
  // Hack Design (Free Design)
  {
    id: "design-hackdesign-1",
    title: "Design Lesson Path for Developers",
    category: "design",
    provider: "Hack Design",
    price: 0,
    rating: 4.5,
    reviewsCount: 52000,
    duration: "50 weeks (self-paced)",
    level: "Beginner",
    link: "https://hackdesign.org/",
    description: "An easy-to-follow design course for programmers and builders. Receive curations of top design articles, videos, and tutorials weekly.",
    features: ["Free registration", "Curated reading lists", "Weekly lessons by design masters", "Interactive challenges"]
  },
  // INE Cybersecurity
  {
    id: "cyber-ine-1",
    title: "eLearnSecurity Certified Penetration Tester (eCPPTv2)",
    category: "cybersecurity",
    provider: "INE",
    price: 24900,
    rating: 4.7,
    reviewsCount: 5400,
    duration: "45 hours",
    level: "Advanced",
    link: "https://ine.com/learning-paths/ecpptv2",
    description: "Master professional network penetration testing. Perform buffer overflows, advanced system exploitation, and professional reporting.",
    features: ["eCPPTv2 Certification exam voucher", "Interactive lab environments", "Full coverage of system exploits", "Access on mobile and desktop"]
  },
  // TryHackMe Cybersecurity
  {
    id: "cyber-tryhackme-1",
    title: "Pre-Security Pathway",
    category: "cybersecurity",
    provider: "TryHackMe",
    price: 1200,
    rating: 4.8,
    reviewsCount: 88200,
    duration: "40 hours",
    level: "Beginner",
    link: "https://tryhackme.com/path/outline/presecurity",
    description: "Learn the foundational cybersecurity concepts: networking, operating systems, and web technologies required to start a security career.",
    features: ["TryHackMe badge & certificate", "Hands-on gamified rooms", "Interactive Linux/Windows targets", "Self-paced study"]
  },
  // fast.ai AI & ML
  {
    id: "ai-fastai-1",
    title: "Practical Deep Learning for Coders",
    category: "aiml",
    provider: "fast.ai",
    price: 0,
    rating: 4.9,
    reviewsCount: 154000,
    duration: "25 hours",
    level: "Intermediate",
    link: "https://course.fast.ai/",
    description: "A free deep learning course for programmers. Learn how to build state-of-the-art computer vision, NLP, and tabular models using fastai and PyTorch.",
    features: ["Free online book & videos", "PyTorch based training", "Active student forum", "Colab / Kaggle integration"]
  },
  // Coursera AI & ML
  {
    id: "ai-coursera-2",
    title: "Deep Learning Specialization",
    category: "aiml",
    provider: "Coursera",
    price: 4099,
    rating: 4.9,
    reviewsCount: 168000,
    duration: "5 months (10 hrs/week)",
    level: "Advanced",
    link: "https://www.coursera.org/specializations/deep-learning",
    description: "Master deep learning foundations from Andrew Ng. Build and train neural networks, CNNs, RNNs, Transformers, and apply them in projects.",
    features: ["Taught by Andrew Ng", "Shareable specialization certificate", "Python programming assignments", "Access to career resources"]
  },
  // HubSpot Digital Marketing
  {
    id: "mkt-hubspot-1",
    title: "Inbound Marketing Certification Course",
    category: "marketing",
    provider: "HubSpot Academy",
    price: 0,
    rating: 4.7,
    reviewsCount: 42300,
    duration: "5 hours",
    level: "Beginner",
    link: "https://academy.hubspot.com/courses/inbound-marketing",
    description: "Learn inbound marketing strategies, content creation, social promotion, conversational growth, and lead nurturing.",
    features: ["Free industry certificate", "15 video lessons", "4 quizzes", "Downloadable templates"]
  },
  // Udemy Digital Marketing
  {
    id: "mkt-udemy-2",
    title: "Social Media Marketing Agency (SMMA) Course",
    category: "marketing",
    provider: "Udemy",
    price: 1699,
    rating: 4.6,
    reviewsCount: 18200,
    duration: "18.5 hours",
    level: "All Levels",
    link: "https://www.udemy.com/courses/search/?q=smma",
    description: "Learn how to build a social media marketing agency from scratch. Find clients, run Facebook ads, and scale operations.",
    features: ["Certificate of completion", "32 downloadable templates", "Lifetime access", "Client contract templates"]
  },
  // KodeKloud Cloud & DevOps
  {
    id: "cloud-kodekloud-1",
    title: "Certified Kubernetes Administrator (CKA)",
    category: "cloudcomputing",
    provider: "KodeKloud",
    price: 4500,
    rating: 4.8,
    reviewsCount: 19400,
    duration: "32 hours",
    level: "Intermediate",
    link: "https://kodekloud.com/courses/certified-kubernetes-administrator-cka/",
    description: "Prepare for the official CNCF CKA exam. Learn Kubernetes architecture, scheduling, service networking, and troubleshooting.",
    features: ["Shareable certificate", "In-browser Kubernetes labs", "Mock exams included", "Doubt support forum"]
  },
  // Udemy Cloud & DevOps
  {
    id: "cloud-udemy-2",
    title: "Docker & Kubernetes: The Practical Guide",
    category: "cloudcomputing",
    provider: "Udemy",
    price: 1499,
    rating: 4.7,
    reviewsCount: 65100,
    duration: "23 hours",
    level: "Beginner",
    link: "https://www.udemy.com/courses/search/?q=docker+kubernetes",
    description: "Learn Docker, Kubernetes, Compose, Swarm and Registry. Build and deploy containerized apps locally and on AWS/GCP.",
    features: ["Certificate of completion", "54 downloadable resources", "Lifetime access", "Full code repository access"]
  },
  // Coursera Project Management
  {
    id: "pm-coursera-2",
    title: "Scrum Master Certification Specialization",
    category: "business",
    provider: "Coursera",
    price: 3299,
    rating: 4.7,
    reviewsCount: 8800,
    duration: "3 months (10 hrs/week)",
    level: "Beginner",
    link: "https://www.coursera.org/specializations/scrum-master",
    description: "Build a strong foundation in Scrum frameworks. Learn to lead agile teams, remove blocker backlogs, and run effective sprint rituals.",
    features: ["Professional specialization certificate", "Agile workspace simulation", "Prep for PSM I exam", "Flexible schedule"]
  },
  // PMI Project Management
  {
    id: "pm-pmi-1",
    title: "Certified Associate in Project Management (CAPM) Prep",
    category: "business",
    provider: "Project Management Institute (PMI)",
    price: 18500,
    rating: 4.5,
    reviewsCount: 12500,
    duration: "23 hours",
    level: "Beginner",
    link: "https://www.pmi.org/certifications/certified-associate-capm",
    description: "Prepare for the CAPM exam. Master foundational project management terminology, agile concepts, and business analysis framework.",
    features: ["Official PMI CAPM prep hours", "Practice questions", "PMBOK guide exercises", "Shareable badge"]
  }
];

export const SEED_JOBS = [
  {
    id: "job-da",
    title: "Data Analyst",
    description: "Data Analysts collect, process, and perform statistical analyses of data to identify trends, create visualizations, and provide actionable insights that drive business decisions.",
    salary: "₹5,50,000 - ₹9,50,000 / year (5.5 - 9.5 LPA)",
    skills: ["SQL", "Python or R", "Tableau / PowerBI", "Excel", "Data Visualization", "Statistics"],
    link: "https://in.linkedin.com/jobs/data-analyst-jobs?position=1&pageNum=0"
  },
  {
    id: "job-sd",
    title: "Software Developer",
    description: "Software Developers design, program, test, and maintain applications and operating systems. They work with product teams to build scalable code that solves user needs.",
    salary: "₹7,50,000 - ₹14,00,000 / year (7.5 - 14 LPA)",
    skills: ["JavaScript/TypeScript", "Python or Java", "Git", "Data Structures", "Algorithms", "Testing"],
    link: "https://in.linkedin.com/jobs/software-engineer-jobs?position=1&pageNum=0"
  },
  {
    id: "job-fs",
    title: "Fullstack Developer",
    description: "Fullstack Developers manage both front-end (user interface) and back-end (database, API, server logic) engineering, providing complete end-to-end solutions for web products.",
    salary: "₹8,50,000 - ₹16,00,000 / year (8.5 - 16 LPA)",
    skills: ["React / Vue / Angular", "Node.js or Python", "SQL & NoSQL Databases", "REST / GraphQL", "Git & CI/CD", "AWS/Cloud Systems"],
    link: "https://in.linkedin.com/jobs/full-stack-developer-jobs?position=1&pageNum=0"
  },
  {
    id: "job-cs",
    title: "Cyber Security Specialist",
    description: "Cybersecurity Specialists protect organizations from digital attacks. They design security systems, run vulnerability assessments, monitor network traffic, and handle threat mitigations.",
    salary: "₹8,00,000 - ₹15,00,000 / year (8 - 15 LPA)",
    skills: ["Network Security", "Linux Systems", "Python scripting", "Ethical Hacking", "Cryptography", "SIEM Tools"],
    link: "https://in.linkedin.com/jobs/cyber-security-jobs?position=1&pageNum=0"
  },
  {
    id: "job-bd",
    title: "Blockchain Developer",
    description: "Blockchain Developers design and build decentralized architectures, protocols, smart contracts, and decentralized applications (DApps) for finance, supply chains, and security sectors.",
    salary: "₹9,50,000 - ₹18,00,000 / year (9.5 - 18 LPA)",
    skills: ["Solidity / Rust", "Cryptography", "Ethereum / Web3.js", "Smart Contracts", "Data Structures", "Node.js"],
    link: "https://in.linkedin.com/jobs/blockchain-developer-jobs?position=1&pageNum=0"
  },
  {
    id: "job-dm",
    title: "Digital Marketer",
    description: "Digital Marketers utilize digital channels (search engines, social media, email, websites) to reach target audiences, drive brand awareness, acquire customers, and analyze performance campaigns.",
    salary: "₹4,50,000 - ₹8,00,000 / year (4.5 - 8 LPA)",
    skills: ["SEO & SEM", "Google Analytics", "Social Media Ads", "Content Strategy", "Email Campaigns", "Copywriting"],
    link: "https://in.linkedin.com/jobs/digital-marketing-jobs?position=1&pageNum=0"
  }
];

export const SEED_INSTITUTES = [
  {
    id: "inst-1",
    name: "Elite Academy of IT & Data Science",
    logo: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=120&q=80",
    coverImage: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80",
    description: "Elite Academy is India's leading offline classroom training center for advanced IT, Web Development, and Data Science certifications. Founded in 2015, we provide physical labs, face-to-face mentorship, and direct placement support in major companies.",
    establishedYear: 2015,
    categories: ["programming", "datascience", "aiml"],
    phone: "+91 98765 43210",
    email: "info@eliteacademy.in",
    website: "https://eliteacademy.in",
    whatsapp: "+919876543210",
    socials: {
      facebook: "https://facebook.com/eliteacademy",
      twitter: "https://twitter.com/eliteacademy",
      linkedin: "https://linkedin.com/company/eliteacademy"
    },
    address: "Plot 42, Viman Nagar Road, Opposite Phoenix Marketcity, Pune, Maharashtra 411014",
    landmarks: ["Phoenix Marketcity Mall", "Viman Nagar Metro Station"],
    city: "Pune",
    state: "Maharashtra",
    coordinates: { lat: 18.5679, lng: 73.9143 },
    infrastructure: ["Air Conditioned Labs", "High Speed Wi-Fi", "Student Discussion Lounge", "Library Access"],
    practicalLabs: true,
    placementRecord: "92% Placements (Average salary of 6.5 LPA)",
    rating: 4.8,
    reviewsCount: 3,
    courses: [
      {
        id: "inst-1-c1",
        title: "Master in Full Stack Web Development (MERN)",
        category: "programming",
        duration: "6 months",
        mode: "Offline",
        fees: 45000,
        batchTimings: "Morning (9:00 AM - 12:00 PM) or Evening (6:00 PM - 9:00 PM)",
        startDate: new Date("2026-08-01"),
        trainerName: "Dr. Alok Sharma (Ex-Tech Lead)",
        certification: "Elite Certified Professional Developer",
        eligibility: "Any Graduate / Final Year Students",
        syllabus: ["HTML5 & CSS3 Essentials", "JavaScript ES6 & DOM", "React.js Frontend Architecture", "Node.js & Express REST APIs", "MongoDB Database Design", "Production Deployment & Git"],
        placementAssistance: true
      },
      {
        id: "inst-1-c2",
        title: "Advanced Data Science & Machine Learning",
        category: "datascience",
        duration: "5 months",
        mode: "Hybrid",
        fees: 60000,
        batchTimings: "Weekend Batch (Saturday & Sunday 10:00 AM - 4:00 PM)",
        startDate: new Date("2026-08-15"),
        trainerName: "Ms. Priya Patel (Data Scientist at TechM)",
        certification: "Certified Data Science Expert",
        eligibility: "B.Tech / MCA / Math / Statistics graduates",
        syllabus: ["Python for Data Science", "NumPy & Pandas Analytics", "SQL & Database Queries", "Supervised Machine Learning", "Unsupervised Clustering", "Tableau & PowerBI Visualizations"],
        placementAssistance: true
      }
    ]
  },
  {
    id: "inst-2",
    name: "Apex Civil Services & Government Coaching",
    logo: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=120&q=80",
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    description: "Apex Coaching is a premier institute specialized in physical coaching for competitive Government Exams, Civil Services (UPSC/MPSC), and Banking exams. We have structured library access, daily mock test centers, and mentorship from retired IAS/IPS officers.",
    establishedYear: 2010,
    categories: ["government", "business"],
    phone: "+91 88888 77777",
    email: "contact@apexexams.org",
    website: "https://apexcoaching.org",
    whatsapp: "+918888877777",
    socials: {
      facebook: "https://facebook.com/apexexams",
      twitter: "https://twitter.com/apexexams",
      linkedin: "https://linkedin.com/company/apexexams"
    },
    address: "128, Sadashiv Peth, Near Lal Mahal, Pune, Maharashtra 411030",
    landmarks: ["Lal Mahal Monument", "Shanivar Wada"],
    city: "Pune",
    state: "Maharashtra",
    coordinates: { lat: 18.5162, lng: 73.8562 },
    infrastructure: ["24/7 Silent Reading Room", "Mock Test Center", "Doubt Solving Cubicles"],
    practicalLabs: false,
    placementRecord: "78% Selection rate in Banking & State exams",
    rating: 4.6,
    reviewsCount: 2,
    courses: [
      {
        id: "inst-2-c1",
        title: "UPSC Civil Services Foundation Course",
        category: "government",
        duration: "12 months",
        mode: "Offline",
        fees: 85000,
        batchTimings: "Regular Batch (10:00 AM - 2:00 PM)",
        startDate: new Date("2026-07-25"),
        trainerName: "Mr. R. K. Verma (Retd. IAS)",
        certification: "Apex UPSC Prep Completion Certificate",
        eligibility: "Graduation completed or pursuing final year",
        syllabus: ["General Studies I (History, Geography)", "General Studies II (Polity, Constitution)", "General Studies III (Economy, Environment)", "CSAT Aptitude & Comprehension", "Essay Writing & Answer Writing Practice", "Mock Interview Prep"],
        placementAssistance: false
      },
      {
        id: "inst-2-c2",
        title: "Banking Exams (IBPS / SBI PO & Clerk) Masterclass",
        category: "government",
        duration: "4 months",
        mode: "Offline",
        fees: 25000,
        batchTimings: "Morning (7:30 AM - 10:00 AM) or Afternoon (2:30 PM - 5:00 PM)",
        startDate: new Date("2026-08-05"),
        trainerName: "Mr. Suresh Kamath (Banking Trainer)",
        certification: "Banking Aptitude Certified",
        eligibility: "Any Graduate",
        syllabus: ["Quantitative Aptitude & Math Shortcuts", "Logical Reasoning & Puzzle Solving", "English Grammar & Vocabulary", "Banking Awareness & Economy", "Mock Test Drills & Speed Tests"],
        placementAssistance: true
      }
    ]
  },
  {
    id: "inst-3",
    name: "TechVantage DevOps & Cyber Security Academy",
    logo: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&q=80",
    coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    description: "TechVantage is a high-tech training laboratory focused exclusively on Devops, Cloud Computing (AWS/Azure), and Cyber Security certifications. We specialize in live sandbox deployments, server configurations, and cybersecurity attack simulations.",
    establishedYear: 2018,
    categories: ["cloudcomputing", "cybersecurity"],
    phone: "+91 99999 11111",
    email: "admission@techvantage.edu",
    website: "https://techvantage.edu",
    whatsapp: "+919999911111",
    socials: {
      facebook: "https://facebook.com/techvantage",
      twitter: "https://twitter.com/techvantage",
      linkedin: "https://linkedin.com/company/techvantage"
    },
    address: "Block B-3, Outer Ring Road, Sector 3, HSR Layout, Bengaluru, Karnataka 560102",
    landmarks: ["HSR Layout BDA Complex", "McDonalds HSR Junction"],
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 12.9141, lng: 77.6413 },
    infrastructure: ["DevOps Simulation Cloud Lab", "High-End Workstations", "Cafeteria & Discussion Rooms"],
    practicalLabs: true,
    placementRecord: "95% Direct placement in Cloud Support roles",
    rating: 4.9,
    reviewsCount: 2,
    courses: [
      {
        id: "inst-3-c1",
        title: "DevOps & Cloud Infrastructure Master Program",
        category: "cloudcomputing",
        duration: "6 months",
        mode: "Offline",
        fees: 75000,
        batchTimings: "Weekend Batch (Saturday & Sunday 9:30 AM - 3:30 PM)",
        startDate: new Date("2026-08-10"),
        trainerName: "Mr. Devendra Gupta (Cloud Solutions Architect)",
        certification: "AWS / DevOps Professional Certified",
        eligibility: "IT professionals or graduates with basic Linux skills",
        syllabus: ["Linux Server Administration", "Git Version Control & CI/CD", "Docker Containers & Kubernetes", "Infrastructure as Code: Terraform", "AWS Cloud Services Essentials", "Ansible Configurations & Monitoring"],
        placementAssistance: true
      },
      {
        id: "inst-3-c2",
        title: "Ethical Hacking & Network Cyber Security Specialist",
        category: "cybersecurity",
        duration: "5 months",
        mode: "Offline",
        fees: 55000,
        batchTimings: "Weekday Batch (Monday to Thursday 3:00 PM - 6:00 PM)",
        startDate: new Date("2026-08-20"),
        trainerName: "Mr. Samyak Naik (Certified Ethical Hacker)",
        certification: "Certified Network Security Specialist",
        eligibility: "Computer Science graduates or IT professionals",
        syllabus: ["Networking & Subnetting Basics", "Footprinting & Port Scanning", "System Hacking & Vulnerability Analysis", "Web Application Penetration Testing", "Cryptography & WireShark Sniffing", "Firewall Setup & Intrusion Detection"],
        placementAssistance: true
      }
    ]
  },
  {
    id: "inst-4",
    name: "DesignEdge Studio Academy",
    logo: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=120&q=80",
    coverImage: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80",
    description: "DesignEdge is a dedicated studio coaching center for creative design, UI/UX interfaces, graphic design, and animation certifications. We offer state-of-the-art Apple iMac suites, sketching studios, and interactive portfolio reviews.",
    establishedYear: 2019,
    categories: ["design"],
    phone: "+91 77777 55555",
    email: "hello@designedge.academy",
    website: "https://designedge.academy",
    whatsapp: "+917777755555",
    socials: {
      facebook: "https://facebook.com/designedgestudio",
      twitter: "https://twitter.com/designedgestudio",
      linkedin: "https://linkedin.com/company/designedgestudio"
    },
    address: "5th Floor, Galleria Towers, DLF Phase 4, Gurugram, Haryana 122002",
    landmarks: ["Galleria Market", "DLF Phase IV Metro Station"],
    city: "Gurugram",
    state: "Haryana",
    coordinates: { lat: 28.4682, lng: 77.0864 },
    infrastructure: ["Apple iMac Creative Lab", "Manual Sketching Studio", "Portfolio Lounge"],
    practicalLabs: true,
    placementRecord: "88% Placements as Product/UI/UX Designers",
    rating: 4.7,
    reviewsCount: 2,
    courses: [
      {
        id: "inst-4-c1",
        title: "Master UI/UX Design & Product Strategy",
        category: "design",
        duration: "6 months",
        mode: "Offline",
        fees: 50000,
        batchTimings: "Morning (10:00 AM - 1:00 PM) or Weekend (Saturday 10:00 AM - 5:00 PM)",
        startDate: new Date("2026-08-01"),
        trainerName: "Mrs. Sneha Sen (Design Lead)",
        certification: "DesignEdge Certified UX Specialist",
        eligibility: "Any Graduate with design interest (no coding needed)",
        syllabus: ["Design Thinking & UX Research", "User Persona & Journey Maps", "Figma Interface Design & Auto Layouts", "Interactive Prototyping & Micro-animations", "Heuristic Evaluation & Usability Testing", "Design Systems & Portfolio Building"],
        placementAssistance: true
      }
    ]
  },
  {
    id: "inst-5",
    name: "DataMites Data Science Coaching",
    logo: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=120&q=80",
    coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    description: "DataMites is a global provider of Data Science, Machine Learning, and Artificial Intelligence certifications. We provide intensive offline boot camps with syllabus mapped to global standards, internship options with live projects, and placement assistance.",
    establishedYear: 2016,
    categories: ["datascience", "aiml"],
    phone: "+91 80 4718 5555",
    email: "info@datamites.com",
    website: "https://datamites.com",
    whatsapp: "+918047185555",
    socials: {
      facebook: "https://facebook.com/datamites",
      twitter: "https://twitter.com/datamites",
      linkedin: "https://linkedin.com/company/datamites"
    },
    address: "DataMites, Sector 4, Near HSR Club, HSR Layout, Bengaluru, Karnataka 560102",
    landmarks: ["HSR Layout Club", "Sector 4 Park"],
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 12.9125, lng: 77.6395 },
    infrastructure: ["Air Conditioned Classrooms", "24/7 Practice Lab Access", "Free Study Materials"],
    practicalLabs: true,
    placementRecord: "90% Placement Assistance (Data Analyst average 5.8 LPA)",
    rating: 4.7,
    reviewsCount: 1,
    courses: [
      {
        id: "inst-5-c1",
        title: "Certified Data Scientist Bootcamp",
        category: "datascience",
        duration: "6 months",
        mode: "Offline",
        fees: 55000,
        batchTimings: "Morning (10:00 AM - 1:00 PM) or Weekend (Saturday & Sunday 10:00 AM - 4:00 PM)",
        startDate: new Date("2026-08-01"),
        trainerName: "Mr. Ashok Kumar (AI Lead)",
        certification: "IABAC Certified Data Scientist",
        eligibility: "Any Graduate with analytical mindset",
        syllabus: ["Python Programming Basics", "Data Analysis with Pandas", "Statistics for Data Science", "Machine Learning Algorithms", "Introduction to Deep Learning", "PowerBI & Tableau Visualizations"],
        placementAssistance: true
      },
      {
        id: "inst-5-c2",
        title: "Artificial Intelligence Foundation",
        category: "aiml",
        duration: "3 months",
        mode: "Offline",
        fees: 35000,
        batchTimings: "Evening Batch (6:30 PM - 8:30 PM)",
        startDate: new Date("2026-08-10"),
        trainerName: "Dr. Sandeep Patel (AI Researcher)",
        certification: "IABAC Certified AI Foundation",
        eligibility: "B.Tech / MCA / Math / Physics graduates",
        syllabus: ["Introduction to AI & Neurons", "Supervised Learning Algorithms", "Neural Networks & Deep Learning", "Computer Vision Basics", "Natural Language Processing (NLP)"],
        placementAssistance: false
      }
    ]
  },
  {
    id: "inst-6",
    name: "ExcelR Raising Careers",
    logo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=120&q=80",
    coverImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80",
    description: "ExcelR is a premier technical training institute offering comprehensive offline classroom programs for Data Science, Business Analytics, and Full Stack Web Development. ExcelR provides classroom coaching across 10+ cities, direct corporate placement tie-ups, and peer learning support.",
    establishedYear: 2013,
    categories: ["datascience", "programming", "business"],
    phone: "+91 91082 38354",
    email: "enquiry@excelr.com",
    website: "https://excelr.com",
    whatsapp: "+919108238354",
    socials: {
      facebook: "https://facebook.com/excelr",
      twitter: "https://twitter.com/excelr",
      linkedin: "https://linkedin.com/company/excelr"
    },
    address: "3rd Floor, Suras Landmark, Baner Road, Opposite Croma, Pune, Maharashtra 411045",
    landmarks: ["Croma Showroom Baner", "Pallod Farms Junction"],
    city: "Pune",
    state: "Maharashtra",
    coordinates: { lat: 18.5595, lng: 73.8055 },
    infrastructure: ["Modern Multi-media Classrooms", "Practical Labs", "Discussion Cubicles", "Placement Cell Lounge"],
    practicalLabs: true,
    placementRecord: "91% Selection Rate (Average salary of 6 LPA)",
    rating: 4.8,
    reviewsCount: 1,
    courses: [
      {
        id: "inst-6-c1",
        title: "Data Science Certification Course Program",
        category: "datascience",
        duration: "6 months",
        mode: "Offline",
        fees: 58000,
        batchTimings: "Morning (9:30 AM - 12:30 PM) or Weekend (Saturday & Sunday 9:30 AM - 3:30 PM)",
        startDate: new Date("2026-08-05"),
        trainerName: "Mr. Vignesh Naidu (Principal Data Scientist)",
        certification: "SGIT Steinbeis Certified Data Scientist",
        eligibility: "Any Graduate (Basic math background preferred)",
        syllabus: ["Python & R programming", "Mathematical Statistics", "Machine Learning models", "Text Mining & NLP", "Forecasting & Time Series", "Project Work & Corporate Prep"],
        placementAssistance: true
      },
      {
        id: "inst-6-c2",
        title: "Business Analyst Certification Program",
        category: "business",
        duration: "4 months",
        mode: "Offline",
        fees: 40000,
        batchTimings: "Evening Batch (5:00 PM - 7:00 PM)",
        startDate: new Date("2026-08-15"),
        trainerName: "Ms. Shalini Sinha (Agile Product Manager)",
        certification: "Certified Business Analyst Professional",
        eligibility: "Any Graduate",
        syllabus: ["Business Analysis Foundations", "Agile & Scrum Frameworks", "SQL & Database Queries", "Tableau & PowerBI reports", "Excel Advanced Analytics", "Requirement Documentation (BRD/FRD)"],
        placementAssistance: true
      }
    ]
  }
];

export const SEED_REVIEWS = [
  {
    instituteId: "inst-5",
    userEmail: "learner@test.com",
    userName: "Sameer Joshi",
    rating: 5,
    text: "Studying Data Science at DataMites Bangalore was a game-changer. The IABAC certification syllabus is very comprehensive, and the practical labs helped clear all statistics concepts.",
    pros: ["Experienced faculty", "IABAC global certification", "Excellent lab support"],
    cons: ["Syllabus is very intensive"],
    likes: 6,
    likedBy: [],
    date: new Date()
  },
  {
    instituteId: "inst-6",
    userEmail: "kiran@cloud.com",
    userName: "Kiran Shah",
    rating: 5,
    text: "ExcelR Baner coaching is excellent. The trainers are working professionals who explain real-world industry scenarios. Got placed in an analytics startup within 3 months!",
    pros: ["Outstanding placements support", "Baner road access is easy", "Corporate prep sessions"],
    cons: ["Parking space is limited"],
    likes: 8,
    likedBy: [],
    date: new Date()
  },
  {
    instituteId: "inst-1",
    userEmail: "nikhil@certifyhub.com",
    userName: "Nikhil Sontakke",
    rating: 5,
    text: "The MERN stack course at Elite Academy is exceptional. The hands-on coding labs and face-to-face mentorship helped me build 4 solid web projects and secure a front-end job within weeks of graduation.",
    pros: ["Experienced trainer", "Excellent infrastructure", "Personalized placement assistance"],
    cons: ["Heavy course workload", "Strict attendance rules"],
    likes: 8,
    likedBy: ["learner@test.com", "arjun@gmail.com"],
    date: new Date()
  },
  {
    instituteId: "inst-1",
    userEmail: "arjun@gmail.com",
    userName: "Arjun Verma",
    rating: 4,
    text: "Great learning environment in Pune. The data science lab is fully equipped and the weekend timings fit perfectly with my tech support job schedules.",
    pros: ["Flexible weekend batches", "AC Classrooms"],
    cons: ["Syllabus moves fast"],
    likes: 3,
    likedBy: ["nikhil@certifyhub.com"],
    date: new Date()
  },
  {
    instituteId: "inst-1",
    userEmail: "neha@outlook.com",
    userName: "Neha Gupta",
    rating: 5,
    text: "I loved the training style. They don't just teach code, they explain systems logic. The mock interviews conducted here gave me massive confidence.",
    pros: ["Detailed syllabus coverage", "Mock interview tests"],
    cons: ["Viman Nagar traffic during peak hours"],
    likes: 4,
    likedBy: ["nikhil@certifyhub.com"],
    date: new Date()
  },
  {
    instituteId: "inst-2",
    userEmail: "rahul@government.in",
    userName: "Rahul Deshmukh",
    rating: 4,
    text: "Very reliable coaching for UPSC prep in Sadashiv Peth. The library access is very helpful, though it can get crowded in the afternoon slots.",
    pros: ["IAS mentors", "Silent reading rooms"],
    cons: ["Library crowd during peak hours"],
    likes: 12,
    likedBy: [],
    date: new Date()
  },
  {
    instituteId: "inst-2",
    userEmail: "shreya@pune.org",
    userName: "Shreya Patil",
    rating: 5,
    text: "Excellent shortcuts taught for Banking quantitative maths! Cleared my SBI Clerk prelims easily after joining their mock test series.",
    pros: ["Brilliant math tips", "Excellent mock test series"],
    cons: ["Classroom has bench seating"],
    likes: 9,
    likedBy: [],
    date: new Date()
  },
  {
    instituteId: "inst-3",
    userEmail: "karan@cloud.com",
    userName: "Karan Johar",
    rating: 5,
    text: "The DevOps labs are fantastic. Configuring servers and deploying Kubernetes clusters in a physical classroom helped clear all my architectural doubts.",
    pros: ["Dedicated sandbox server lab", "Industry certified trainers"],
    cons: ["High fees compared to online"],
    likes: 5,
    likedBy: [],
    date: new Date()
  },
  {
    instituteId: "inst-4",
    userEmail: "ananya@design.in",
    userName: "Ananya Roy",
    rating: 5,
    text: "Top tier design school in Gurugram! Working on Figma and sketching mockups alongside other designers in the Apple iMac lab was a wonderful experience.",
    pros: ["Apple iMac workspace", "Excellent portfolio feedback sessions"],
    cons: ["Parking fees at Galleria tower"],
    likes: 7,
    likedBy: [],
    date: new Date()
  }
];
